/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Origin Organization I-REC API
 * Swagger documentation for the Origin Organization I-REC API
 * OpenAPI spec version: 0.1
 */
export type IRECAccountType = 'Registrant' | 'Participant' | 'Both';

export const IRECAccountType = {
  Registrant: 'Registrant' as IRECAccountType,
  Participant: 'Participant' as IRECAccountType,
  Both: 'Both' as IRECAccountType,
};

export interface RegistrationDTO {
  accountType: IRECAccountType;
  headquarterCountry: string;
  registrationYear: number;
  employeesNumber: string;
  shareholders: string;
  website: string;
  activeCountries: string[];
  mainBusiness: string;
  ceoName: string;
  ceoPassportNumber: string;
  balanceSheetTotal: string;
  subsidiaries?: string;
  primaryContactOrganizationName: string;
  primaryContactOrganizationAddress: string;
  primaryContactOrganizationPostalCode: string;
  primaryContactOrganizationCountry: string;
  primaryContactName: string;
  primaryContactEmail: string;
  primaryContactPhoneNumber: string;
  primaryContactFax: string;
  leadUserTitle: string;
  leadUserFirstName: string;
  leadUserLastName: string;
  leadUserEmail: string;
  leadUserPhoneNumber: string;
  leadUserFax: string;
  id: string;
  owner: string;
}

export interface NewRegistrationDTO {
  accountType: IRECAccountType;
  headquarterCountry: string;
  registrationYear: number;
  employeesNumber: string;
  shareholders: string;
  website: string;
  activeCountries: string[];
  mainBusiness: string;
  ceoName: string;
  ceoPassportNumber: string;
  balanceSheetTotal: string;
  subsidiaries?: string;
  primaryContactOrganizationName: string;
  primaryContactOrganizationAddress: string;
  primaryContactOrganizationPostalCode: string;
  primaryContactOrganizationCountry: string;
  primaryContactName: string;
  primaryContactEmail: string;
  primaryContactPhoneNumber: string;
  primaryContactFax: string;
  leadUserTitle: string;
  leadUserFirstName: string;
  leadUserLastName: string;
  leadUserEmail: string;
  leadUserPhoneNumber: string;
  leadUserFax: string;
}

export interface RegisterResponseDTO {
  id: string;
}

export interface CreateConnectionDTO {
  userName: string;
  password: string;
  clientId: string;
  clientSecret: string;
}

export interface ConnectionDTO {
  accessToken: string;
  refreshToken: string;
  expiryDate: string;
  registration: RegistrationDTO;
}
