export const deviceTypes = [
  ['Solar'],
  ['Solar', 'Photovoltaic'],
  ['Solar', 'Photovoltaic', 'Roof mounted'],
  ['Solar', 'Photovoltaic', 'Ground mounted'],
  ['Solar', 'Photovoltaic', 'Classic silicon'],
  ['Solar', 'Concentration'],
  ['Wind'],
  ['Wind', 'Onshore'],
  ['Wind', 'Offshore'],
  ['Hydro-electric Head'],
  ['Hydro-electric Head', 'Run-of-river head installation'],
  ['Hydro-electric Head', 'Storage head installation'],
  ['Hydro-electric Head', 'Pure pumped storage head installation'],
  ['Hydro-electric Head', 'Mixed pumped storage head'],
  ['Marine'],
  ['Marine', 'Tidal'],
  ['Marine', 'Tidal', 'Inshore'],
  ['Marine', 'Tidal', 'Offshore'],
  ['Marine', 'Wave'],
  ['Marine', 'Wave', 'Onshore'],
  ['Marine', 'Wave', 'Offshore'],
  ['Marine', 'Currents'],
  ['Marine', 'Pressure'],
  ['Marine', 'Thermal'],
  ['Solid'],
  ['Solid', 'Muncipal waste'],
  ['Solid', 'Muncipal waste', 'Biogenic'],
  ['Solid', 'Industrial and commercial waste'],
  ['Solid', 'Industrial and commercial waste', 'Biogenic'],
  ['Solid', 'Wood'],
  ['Solid', 'Wood', 'Forestry products'],
  ['Solid', 'Wood', 'Forestry by-products & waste'],
  ['Solid', 'Animal fats'],
  ['Solid', 'Biomass from agriculture'],
  ['Solid', 'Biomass from agriculture', 'Agricultural products'],
  ['Solid', 'Biomass from agriculture', 'Agricultural by-products & waste'],
  ['Liquid'],
  ['Liquid', 'Municipal biodegradable waste'],
  ['Liquid', 'Black liquor'],
  ['Liquid', 'Pure plant oil'],
  ['Liquid', 'Waste plant oil'],
  ['Liquid', 'Refined vegetable oil'],
  ['Liquid', 'Refined vegetable oil', 'Biodiesel (mono-alkyl ester)'],
  ['Liquid', 'Refined vegetable oil', 'Biogasoline (C6-C12 hydrocarbon)'],
  ['Gaseous'],
  ['Gaseous', 'Landfill gas'],
  ['Gaseous', 'Sewage gas'],
  ['Gaseous', 'Agricultural gas'],
  ['Gaseous', 'Agricultural gas', 'Animal manure'],
  ['Gaseous', 'Agricultural gas', 'Energy crops'],
  ['Gaseous', 'Gas from organic waste digestion'],
  ['Gaseous', 'Process gas'],
  ['Gaseous', 'Process gas', 'Biogenic'],
  ['Thermal'],
  ['Thermal', 'Internal combustion engine'],
  ['Thermal', 'Internal combustion engine', 'Non CHP'],
  ['Thermal', 'Internal combustion engine', 'CHP'],
  ['Thermal', 'Steam turbine with condensation turbine'],
  ['Thermal', 'Steam turbine with condensation turbine', 'Non CHP'],
];
