/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Exchange I-REC API
 * Swagger documentation for the Exchange I-REC API
 * OpenAPI spec version: 0.1
 */
import { useQuery, UseQueryOptions } from 'react-query';
import type { AssetDTO } from './exchangeIRECAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const assetControllerGet = <Data = unknown>(id: string) => {
  return customMutator<Data extends unknown ? AssetDTO : Data>({
    url: `/api/asset/${id}`,
    method: 'get',
  });
};

export const getAssetControllerGetQueryKey = (id: string) => [
  `/api/asset/${id}`,
];

export const useAssetControllerGet = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  id: string,
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof assetControllerGet>,
    Error
  >
) => {
  const queryKey = getAssetControllerGetQueryKey(id);

  const query = useQuery<AsyncReturnType<typeof assetControllerGet>, Error>(
    queryKey,
    () => assetControllerGet<Data>(id),
    { enabled: !!id, ...queryConfig }
  );

  return {
    queryKey,
    ...query,
  };
};
