/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Exchange API
 * Swagger documentation for the Exchange API
 * OpenAPI spec version: 0.1
 */
import { useQuery, UseQueryOptions } from 'react-query';
import type { AccountBalanceDTO } from './exchangeAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const accountBalanceControllerGet = <Data = unknown>() => {
  return customMutator<Data extends unknown ? AccountBalanceDTO : Data>({
    url: `/api/account-balance`,
    method: 'get',
  });
};

export const getAccountBalanceControllerGetQueryKey = () => [
  `/api/account-balance`,
];

export const useAccountBalanceControllerGet = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof accountBalanceControllerGet>,
    Error
  >
) => {
  const queryKey = getAccountBalanceControllerGetQueryKey();

  const query = useQuery<
    AsyncReturnType<typeof accountBalanceControllerGet>,
    Error
  >(queryKey, () => accountBalanceControllerGet<Data>(), queryConfig);

  return {
    queryKey,
    ...query,
  };
};
