/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Exchange API
 * Swagger documentation for the Exchange API
 * OpenAPI spec version: 0.1
 */
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
} from 'react-query';
import type {
  Transfer,
  RequestWithdrawalDTO,
  RequestClaimDTO,
} from './exchangeAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const transferControllerGetMyTransfers = <Data = unknown>() => {
  return customMutator<Data extends unknown ? Transfer[] : Data>({
    url: `/api/transfer/all`,
    method: 'get',
  });
};

export const getTransferControllerGetMyTransfersQueryKey = () => [
  `/api/transfer/all`,
];

export const useTransferControllerGetMyTransfers = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof transferControllerGetMyTransfers>,
    Error
  >
) => {
  const queryKey = getTransferControllerGetMyTransfersQueryKey();

  const query = useQuery<
    AsyncReturnType<typeof transferControllerGetMyTransfers>,
    Error
  >(queryKey, () => transferControllerGetMyTransfers<Data>(), queryConfig);

  return {
    queryKey,
    ...query,
  };
};

export const transferControllerRequestWithdrawal = <Data = unknown>(
  requestWithdrawalDTO: RequestWithdrawalDTO
) => {
  return customMutator<Data extends unknown ? string : Data>({
    url: `/api/transfer/withdrawal`,
    method: 'post',
    data: requestWithdrawalDTO,
  });
};

export const useTransferControllerRequestWithdrawal = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  mutationConfig?: UseMutationOptions<
    AsyncReturnType<typeof transferControllerRequestWithdrawal>,
    Error,
    { data: RequestWithdrawalDTO }
  >
) => {
  return useMutation<
    AsyncReturnType<typeof transferControllerRequestWithdrawal>,
    Error,
    { data: RequestWithdrawalDTO }
  >((props) => {
    const { data } = props || {};

    return transferControllerRequestWithdrawal<Data>(data);
  }, mutationConfig);
};
export const transferControllerRequestClaim = <Data = unknown>(
  requestClaimDTO: RequestClaimDTO
) => {
  return customMutator<Data extends unknown ? string : Data>({
    url: `/api/transfer/claim`,
    method: 'post',
    data: requestClaimDTO,
  });
};

export const useTransferControllerRequestClaim = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  mutationConfig?: UseMutationOptions<
    AsyncReturnType<typeof transferControllerRequestClaim>,
    Error,
    { data: RequestClaimDTO }
  >
) => {
  return useMutation<
    AsyncReturnType<typeof transferControllerRequestClaim>,
    Error,
    { data: RequestClaimDTO }
  >((props) => {
    const { data } = props || {};

    return transferControllerRequestClaim<Data>(data);
  }, mutationConfig);
};
