/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Origin Device Registry I-REC Local API
 * Swagger documentation for the Origin Device Registry I-REC Local API
 * OpenAPI spec version: 0.1
 */
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
} from 'react-query';
import type {
  ConnectionDTO,
  CreateConnectionDTO,
} from './originDeviceRegistryIRECLocalAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const connectionControllerRegister = <Data = unknown>(
  createConnectionDTO: CreateConnectionDTO
) => {
  return customMutator<Data extends unknown ? ConnectionDTO : Data>({
    url: `/api/irec/connection`,
    method: 'post',
    data: createConnectionDTO,
  });
};

export const useConnectionControllerRegister = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  mutationConfig?: UseMutationOptions<
    AsyncReturnType<typeof connectionControllerRegister>,
    Error,
    { data: CreateConnectionDTO }
  >
) => {
  return useMutation<
    AsyncReturnType<typeof connectionControllerRegister>,
    Error,
    { data: CreateConnectionDTO }
  >((props) => {
    const { data } = props || {};

    return connectionControllerRegister<Data>(data);
  }, mutationConfig);
};
export const connectionControllerGetMyConnection = <Data = unknown>() => {
  return customMutator<Data extends unknown ? ConnectionDTO[] : Data>({
    url: `/api/irec/connection`,
    method: 'get',
  });
};

export const getConnectionControllerGetMyConnectionQueryKey = () => [
  `/api/irec/connection`,
];

export const useConnectionControllerGetMyConnection = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof connectionControllerGetMyConnection>,
    Error
  >
) => {
  const queryKey = getConnectionControllerGetMyConnectionQueryKey();

  const query = useQuery<
    AsyncReturnType<typeof connectionControllerGetMyConnection>,
    Error
  >(queryKey, () => connectionControllerGetMyConnection<Data>(), queryConfig);

  return {
    queryKey,
    ...query,
  };
};
