/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Origin Backend API
 * Swagger documentation for the Origin Backend API
 * OpenAPI spec version: 0.1
 */
import { useMutation, UseMutationOptions } from 'react-query';
import type {
  LoginReturnDataDTO,
  LoginDataDTO,
} from './originBackendAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const appControllerLogin = <Data = unknown>(
  loginDataDTO: LoginDataDTO
) => {
  return customMutator<Data extends unknown ? LoginReturnDataDTO : Data>({
    url: `/api/auth/login`,
    method: 'post',
    data: loginDataDTO,
  });
};

export const useAppControllerLogin = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  mutationConfig?: UseMutationOptions<
    AsyncReturnType<typeof appControllerLogin>,
    Error,
    { data: LoginDataDTO }
  >
) => {
  return useMutation<
    AsyncReturnType<typeof appControllerLogin>,
    Error,
    { data: LoginDataDTO }
  >((props) => {
    const { data } = props || {};

    return appControllerLogin<Data>(data);
  }, mutationConfig);
};
