export enum MatchingErrorReason {
    NON_ACTIVE_DEMAND,
    NOT_ENOUGH_ENERGY,
    TOO_EXPENSIVE,
    NON_MATCHING_CURRENCY,
    NON_MATCHING_ASSET_TYPE,
    WRONG_ASSET_ID,
    OUT_OF_RANGE,
    NON_MATCHING_LOCATION
}
