/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Origin Device Registry API
 * Swagger documentation for the Origin Device Registry API
 * OpenAPI spec version: 0.1
 */
export interface ExternalDeviceIdDTO {
  id: string;
  type: string;
}

export interface OriginDeviceDTO {
  externalRegistryId: string;
  smartMeterId: string;
  description: string;
  externalDeviceIds?: ExternalDeviceIdDTO[];
  imageIds?: string[];
  id: string;
  owner: string;
}

export interface NewDeviceDTO {
  externalRegistryId: string;
  smartMeterId: string;
  description: string;
  externalDeviceIds?: ExternalDeviceIdDTO[];
  imageIds?: string[];
}
