/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Exchange I-REC API
 * Swagger documentation for the Exchange I-REC API
 * OpenAPI spec version: 0.1
 */
import { useQuery, UseQueryOptions } from 'react-query';
import type { TradeDTO } from './exchangeIRECAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const tradeControllerGetAll = <Data = unknown>() => {
  return customMutator<Data extends unknown ? TradeDTO[] : Data>({
    url: `/api/trade`,
    method: 'get',
  });
};

export const getTradeControllerGetAllQueryKey = () => [`/api/trade`];

export const useTradeControllerGetAll = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof tradeControllerGetAll>,
    Error
  >
) => {
  const queryKey = getTradeControllerGetAllQueryKey();

  const query = useQuery<AsyncReturnType<typeof tradeControllerGetAll>, Error>(
    queryKey,
    () => tradeControllerGetAll<Data>(),
    queryConfig
  );

  return {
    queryKey,
    ...query,
  };
};
