// @should move to utils package && use import from @energyweb/utils-general
export const Countries = [
  {
    id: 1,
    code: 'AF',
    name: 'Afghanistan',
    slug: 'afghanistan',
  },
  {
    id: 2,
    code: 'AX',
    name: 'Åland Islands',
    slug: 'aland-islands',
  },
  {
    id: 3,
    code: 'AL',
    name: 'Albania',
    slug: 'albania',
  },
  {
    id: 4,
    code: 'DZ',
    name: 'Algeria',
    slug: 'algeria',
  },
  {
    id: 5,
    code: 'AS',
    name: 'American Samoa',
    slug: 'american-samoa',
  },
  {
    id: 6,
    code: 'AD',
    name: 'Andorra',
    slug: 'andorra',
  },
  {
    id: 7,
    code: 'AO',
    name: 'Angola',
    slug: 'angola',
  },
  {
    id: 8,
    code: 'AI',
    name: 'Anguilla',
    slug: 'anguilla',
  },
  {
    id: 9,
    code: 'AQ',
    name: 'Antarctica',
    slug: 'antarctica',
  },
  {
    id: 10,
    code: 'AG',
    name: 'Antigua and Barbuda',
    slug: 'antigua-and-barbuda',
  },
  {
    id: 11,
    code: 'AR',
    name: 'Argentina',
    slug: 'argentina',
  },
  {
    id: 12,
    code: 'AM',
    name: 'Armenia',
    slug: 'armenia',
  },
  {
    id: 13,
    code: 'AW',
    name: 'Aruba',
    slug: 'aruba',
  },
  {
    id: 14,
    code: 'AU',
    name: 'Australia',
    slug: 'australia',
  },
  {
    id: 15,
    code: 'AT',
    name: 'Austria',
    slug: 'austria',
  },
  {
    id: 16,
    code: 'AZ',
    name: 'Azerbaijan',
    slug: 'azerbaijan',
  },
  {
    id: 17,
    code: 'BS',
    name: 'Bahamas',
    slug: 'bahamas',
  },
  {
    id: 18,
    code: 'BH',
    name: 'Bahrain',
    slug: 'bahrain',
  },
  {
    id: 19,
    code: 'BD',
    name: 'Bangladesh',
    slug: 'bangladesh',
  },
  {
    id: 20,
    code: 'BB',
    name: 'Barbados',
    slug: 'barbados',
  },
  {
    id: 21,
    code: 'BY',
    name: 'Belarus',
    slug: 'belarus',
  },
  {
    id: 22,
    code: 'BE',
    name: 'Belgium',
    slug: 'belgium',
  },
  {
    id: 23,
    code: 'BZ',
    name: 'Belize',
    slug: 'belize',
  },
  {
    id: 24,
    code: 'BJ',
    name: 'Benin',
    slug: 'benin',
  },
  {
    id: 25,
    code: 'BM',
    name: 'Bermuda',
    slug: 'bermuda',
  },
  {
    id: 26,
    code: 'BT',
    name: 'Bhutan',
    slug: 'bhutan',
  },
  {
    id: 27,
    code: 'BO',
    name: 'Bolivia, Plurinational State of',
    slug: 'bolivia-plurinational-state-of',
  },
  {
    id: 28,
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    slug: 'bonaire-sint-eustatius-and-saba',
  },
  {
    id: 29,
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    slug: 'bosnia-and-herzegovina',
  },
  {
    id: 30,
    code: 'BW',
    name: 'Botswana',
    slug: 'botswana',
  },
  {
    id: 31,
    code: 'BV',
    name: 'Bouvet Island',
    slug: 'bouvet-island',
  },
  {
    id: 32,
    code: 'BR',
    name: 'Brazil',
    slug: 'brazil',
  },
  {
    id: 33,
    code: 'IO',
    name: 'British Indian Ocean Territory',
    slug: 'british-indian-ocean-territory',
  },
  {
    id: 34,
    code: 'BN',
    name: 'Brunei Darussalam',
    slug: 'brunei-darussalam',
  },
  {
    id: 35,
    code: 'BG',
    name: 'Bulgaria',
    slug: 'bulgaria',
  },
  {
    id: 36,
    code: 'BF',
    name: 'Burkina Faso',
    slug: 'burkina-faso',
  },
  {
    id: 37,
    code: 'BI',
    name: 'Burundi',
    slug: 'burundi',
  },
  {
    id: 38,
    code: 'KH',
    name: 'Cambodia',
    slug: 'cambodia',
  },
  {
    id: 39,
    code: 'CM',
    name: 'Cameroon',
    slug: 'cameroon',
  },
  {
    id: 40,
    code: 'CA',
    name: 'Canada',
    slug: 'canada',
  },
  {
    id: 41,
    code: 'CV',
    name: 'Cape Verde',
    slug: 'cape-verde',
  },
  {
    id: 42,
    code: 'KY',
    name: 'Cayman Islands',
    slug: 'cayman-islands',
  },
  {
    id: 43,
    code: 'CF',
    name: 'Central African Republic',
    slug: 'central-african-republic',
  },
  {
    id: 44,
    code: 'TD',
    name: 'Chad',
    slug: 'chad',
  },
  {
    id: 45,
    code: 'CL',
    name: 'Chile',
    slug: 'chile',
  },
  {
    id: 46,
    code: 'CN',
    name: 'China',
    slug: 'china',
  },
  {
    id: 47,
    code: 'CX',
    name: 'Christmas Island',
    slug: 'christmas-island',
  },
  {
    id: 48,
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    slug: 'cocos-keeling-islands',
  },
  {
    id: 49,
    code: 'CO',
    name: 'Colombia',
    slug: 'colombia',
  },
  {
    id: 50,
    code: 'KM',
    name: 'Comoros',
    slug: 'comoros',
  },
  {
    id: 51,
    code: 'CG',
    name: 'Congo',
    slug: 'congo',
  },
  {
    id: 52,
    code: 'CD',
    name: 'Congo, the Democratic Republic of the',
    slug: 'congo-the-democratic-republic-of-the',
  },
  {
    id: 53,
    code: 'CK',
    name: 'Cook Islands',
    slug: 'cook-islands',
  },
  {
    id: 54,
    code: 'CR',
    name: 'Costa Rica',
    slug: 'costa-rica',
  },
  {
    id: 55,
    code: 'CI',
    name: "Côte d'Ivoire",
    slug: 'cote-divoire',
  },
  {
    id: 56,
    code: 'HR',
    name: 'Croatia',
    slug: 'croatia',
  },
  {
    id: 57,
    code: 'CU',
    name: 'Cuba',
    slug: 'cuba',
  },
  {
    id: 58,
    code: 'CW',
    name: 'Curaçao',
    slug: 'curacao',
  },
  {
    id: 59,
    code: 'CY',
    name: 'Cyprus',
    slug: 'cyprus',
  },
  {
    id: 60,
    code: 'CZ',
    name: 'Czech Republic',
    slug: 'czech-republic',
  },
  {
    id: 61,
    code: 'DK',
    name: 'Denmark',
    slug: 'denmark',
  },
  {
    id: 62,
    code: 'DJ',
    name: 'Djibouti',
    slug: 'djibouti',
  },
  {
    id: 63,
    code: 'DM',
    name: 'Dominica',
    slug: 'dominica',
  },
  {
    id: 64,
    code: 'DO',
    name: 'Dominican Republic',
    slug: 'dominican-republic',
  },
  {
    id: 65,
    code: 'EC',
    name: 'Ecuador',
    slug: 'ecuador',
  },
  {
    id: 66,
    code: 'EG',
    name: 'Egypt',
    slug: 'egypt',
  },
  {
    id: 67,
    code: 'SV',
    name: 'El Salvador',
    slug: 'el-salvador',
  },
  {
    id: 68,
    code: 'GQ',
    name: 'Equatorial Guinea',
    slug: 'equatorial-guinea',
  },
  {
    id: 69,
    code: 'ER',
    name: 'Eritrea',
    slug: 'eritrea',
  },
  {
    id: 70,
    code: 'EE',
    name: 'Estonia',
    slug: 'estonia',
  },
  {
    id: 71,
    code: 'ET',
    name: 'Ethiopia',
    slug: 'ethiopia',
  },
  {
    id: 72,
    code: 'FK',
    name: 'Falkland Islands (Malvinas)',
    slug: 'falkland-islands-malvinas',
  },
  {
    id: 73,
    code: 'FO',
    name: 'Faroe Islands',
    slug: 'faroe-islands',
  },
  {
    id: 74,
    code: 'FJ',
    name: 'Fiji',
    slug: 'fiji',
  },
  {
    id: 75,
    code: 'FI',
    name: 'Finland',
    slug: 'finland',
  },
  {
    id: 76,
    code: 'FR',
    name: 'France',
    slug: 'france',
  },
  {
    id: 77,
    code: 'GF',
    name: 'French Guiana',
    slug: 'french-guiana',
  },
  {
    id: 78,
    code: 'PF',
    name: 'French Polynesia',
    slug: 'french-polynesia',
  },
  {
    id: 79,
    code: 'TF',
    name: 'French Southern Territories',
    slug: 'french-southern-territories',
  },
  {
    id: 80,
    code: 'GA',
    name: 'Gabon',
    slug: 'gabon',
  },
  {
    id: 81,
    code: 'GM',
    name: 'Gambia',
    slug: 'gambia',
  },
  {
    id: 82,
    code: 'GE',
    name: 'Georgia',
    slug: 'georgia',
  },
  {
    id: 83,
    code: 'DE',
    name: 'Germany',
    slug: 'germany',
  },
  {
    id: 84,
    code: 'GH',
    name: 'Ghana',
    slug: 'ghana',
  },
  {
    id: 85,
    code: 'GI',
    name: 'Gibraltar',
    slug: 'gibraltar',
  },
  {
    id: 86,
    code: 'GR',
    name: 'Greece',
    slug: 'greece',
  },
  {
    id: 87,
    code: 'GL',
    name: 'Greenland',
    slug: 'greenland',
  },
  {
    id: 88,
    code: 'GD',
    name: 'Grenada',
    slug: 'grenada',
  },
  {
    id: 89,
    code: 'GP',
    name: 'Guadeloupe',
    slug: 'guadeloupe',
  },
  {
    id: 90,
    code: 'GU',
    name: 'Guam',
    slug: 'guam',
  },
  {
    id: 91,
    code: 'GT',
    name: 'Guatemala',
    slug: 'guatemala',
  },
  {
    id: 92,
    code: 'GG',
    name: 'Guernsey',
    slug: 'guernsey',
  },
  {
    id: 93,
    code: 'GN',
    name: 'Guinea',
    slug: 'guinea',
  },
  {
    id: 94,
    code: 'GW',
    name: 'Guinea-Bissau',
    slug: 'guinea-bissau',
  },
  {
    id: 95,
    code: 'GY',
    name: 'Guyana',
    slug: 'guyana',
  },
  {
    id: 96,
    code: 'HT',
    name: 'Haiti',
    slug: 'haiti',
  },
  {
    id: 97,
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    slug: 'heard-island-and-mcdonald-islands',
  },
  {
    id: 98,
    code: 'VA',
    name: 'Holy See (Vatican City State)',
    slug: 'holy-see-vatican-city-state',
  },
  {
    id: 99,
    code: 'HN',
    name: 'Honduras',
    slug: 'honduras',
  },
  {
    id: 100,
    code: 'HK',
    name: 'Hong Kong',
    slug: 'hong-kong',
  },
  {
    id: 101,
    code: 'HU',
    name: 'Hungary',
    slug: 'hungary',
  },
  {
    id: 102,
    code: 'IS',
    name: 'Iceland',
    slug: 'iceland',
  },
  {
    id: 103,
    code: 'IN',
    name: 'India',
    slug: 'india',
  },
  {
    id: 104,
    code: 'ID',
    name: 'Indonesia',
    slug: 'indonesia',
  },
  {
    id: 105,
    code: 'IR',
    name: 'Iran, Islamic Republic of',
    slug: 'iran-islamic-republic-of',
  },
  {
    id: 106,
    code: 'IQ',
    name: 'Iraq',
    slug: 'iraq',
  },
  {
    id: 107,
    code: 'IE',
    name: 'Ireland',
    slug: 'ireland',
  },
  {
    id: 108,
    code: 'IM',
    name: 'Isle of Man',
    slug: 'isle-of-man',
  },
  {
    id: 109,
    code: 'IL',
    name: 'Israel',
    slug: 'israel',
  },
  {
    id: 110,
    code: 'IT',
    name: 'Italy',
    slug: 'italy',
  },
  {
    id: 111,
    code: 'JM',
    name: 'Jamaica',
    slug: 'jamaica',
  },
  {
    id: 112,
    code: 'JP',
    name: 'Japan',
    slug: 'japan',
  },
  {
    id: 113,
    code: 'JE',
    name: 'Jersey',
    slug: 'jersey',
  },
  {
    id: 114,
    code: 'JO',
    name: 'Jordan',
    slug: 'jordan',
  },
  {
    id: 115,
    code: 'KZ',
    name: 'Kazakhstan',
    slug: 'kazakhstan',
  },
  {
    id: 116,
    code: 'KE',
    name: 'Kenya',
    slug: 'kenya',
  },
  {
    id: 117,
    code: 'KI',
    name: 'Kiribati',
    slug: 'kiribati',
  },
  {
    id: 118,
    code: 'KP',
    name: "Korea, Democratic People's Republic of",
    slug: 'korea-democratic-peoples-republic-of',
  },
  {
    id: 119,
    code: 'KR',
    name: 'Korea, Republic of',
    slug: 'korea-republic-of',
  },
  {
    id: 120,
    code: 'KW',
    name: 'Kuwait',
    slug: 'kuwait',
  },
  {
    id: 121,
    code: 'KG',
    name: 'Kyrgyzstan',
    slug: 'kyrgyzstan',
  },
  {
    id: 122,
    code: 'LA',
    name: "Lao People's Democratic Republic",
    slug: 'lao-peoples-democratic-republic',
  },
  {
    id: 123,
    code: 'LV',
    name: 'Latvia',
    slug: 'latvia',
  },
  {
    id: 124,
    code: 'LB',
    name: 'Lebanon',
    slug: 'lebanon',
  },
  {
    id: 125,
    code: 'LS',
    name: 'Lesotho',
    slug: 'lesotho',
  },
  {
    id: 126,
    code: 'LR',
    name: 'Liberia',
    slug: 'liberia',
  },
  {
    id: 127,
    code: 'LY',
    name: 'Libya',
    slug: 'libya',
  },
  {
    id: 128,
    code: 'LI',
    name: 'Liechtenstein',
    slug: 'liechtenstein',
  },
  {
    id: 129,
    code: 'LT',
    name: 'Lithuania',
    slug: 'lithuania',
  },
  {
    id: 130,
    code: 'LU',
    name: 'Luxembourg',
    slug: 'luxembourg',
  },
  {
    id: 131,
    code: 'MO',
    name: 'Macao',
    slug: 'macao',
  },
  {
    id: 132,
    code: 'MK',
    name: 'Macedonia, the Former Yugoslav Republic of',
    slug: 'macedonia-the-former-yugoslav-republic-of',
  },
  {
    id: 133,
    code: 'MG',
    name: 'Madagascar',
    slug: 'madagascar',
  },
  {
    id: 134,
    code: 'MW',
    name: 'Malawi',
    slug: 'malawi',
  },
  {
    id: 135,
    code: 'MY',
    name: 'Malaysia',
    slug: 'malaysia',
  },
  {
    id: 136,
    code: 'MV',
    name: 'Maldives',
    slug: 'maldives',
  },
  {
    id: 137,
    code: 'ML',
    name: 'Mali',
    slug: 'mali',
  },
  {
    id: 138,
    code: 'MT',
    name: 'Malta',
    slug: 'malta',
  },
  {
    id: 139,
    code: 'MH',
    name: 'Marshall Islands',
    slug: 'marshall-islands',
  },
  {
    id: 140,
    code: 'MQ',
    name: 'Martinique',
    slug: 'martinique',
  },
  {
    id: 141,
    code: 'MR',
    name: 'Mauritania',
    slug: 'mauritania',
  },
  {
    id: 142,
    code: 'MU',
    name: 'Mauritius',
    slug: 'mauritius',
  },
  {
    id: 143,
    code: 'YT',
    name: 'Mayotte',
    slug: 'mayotte',
  },
  {
    id: 144,
    code: 'MX',
    name: 'Mexico',
    slug: 'mexico',
  },
  {
    id: 145,
    code: 'FM',
    name: 'Micronesia, Federated States of',
    slug: 'micronesia-federated-states-of',
  },
  {
    id: 146,
    code: 'MD',
    name: 'Moldova, Republic of',
    slug: 'moldova-republic-of',
  },
  {
    id: 147,
    code: 'MC',
    name: 'Monaco',
    slug: 'monaco',
  },
  {
    id: 148,
    code: 'MN',
    name: 'Mongolia',
    slug: 'mongolia',
  },
  {
    id: 149,
    code: 'ME',
    name: 'Montenegro',
    slug: 'montenegro',
  },
  {
    id: 150,
    code: 'MS',
    name: 'Montserrat',
    slug: 'montserrat',
  },
  {
    id: 151,
    code: 'MA',
    name: 'Morocco',
    slug: 'morocco',
  },
  {
    id: 152,
    code: 'MZ',
    name: 'Mozambique',
    slug: 'mozambique',
  },
  {
    id: 153,
    code: 'MM',
    name: 'Myanmar',
    slug: 'myanmar',
  },
  {
    id: 154,
    code: 'NA',
    name: 'Namibia',
    slug: 'namibia',
  },
  {
    id: 155,
    code: 'NR',
    name: 'Nauru',
    slug: 'nauru',
  },
  {
    id: 156,
    code: 'NP',
    name: 'Nepal',
    slug: 'nepal',
  },
  {
    id: 157,
    code: 'NL',
    name: 'Netherlands',
    slug: 'netherlands',
  },
  {
    id: 158,
    code: 'NC',
    name: 'New Caledonia',
    slug: 'new-caledonia',
  },
  {
    id: 159,
    code: 'NZ',
    name: 'New Zealand',
    slug: 'new-zealand',
  },
  {
    id: 160,
    code: 'NI',
    name: 'Nicaragua',
    slug: 'nicaragua',
  },
  {
    id: 161,
    code: 'NE',
    name: 'Niger',
    slug: 'niger',
  },
  {
    id: 162,
    code: 'NG',
    name: 'Nigeria',
    slug: 'nigeria',
  },
  {
    id: 163,
    code: 'NU',
    name: 'Niue',
    slug: 'niue',
  },
  {
    id: 164,
    code: 'NF',
    name: 'Norfolk Island',
    slug: 'norfolk-island',
  },
  {
    id: 165,
    code: 'MP',
    name: 'Northern Mariana Islands',
    slug: 'northern-mariana-islands',
  },
  {
    id: 166,
    code: 'NO',
    name: 'Norway',
    slug: 'norway',
  },
  {
    id: 167,
    code: 'OM',
    name: 'Oman',
    slug: 'oman',
  },
  {
    id: 168,
    code: 'PK',
    name: 'Pakistan',
    slug: 'pakistan',
  },
  {
    id: 169,
    code: 'PW',
    name: 'Palau',
    slug: 'palau',
  },
  {
    id: 170,
    code: 'PS',
    name: 'Palestine, State of',
    slug: 'palestine-state-of',
  },
  {
    id: 171,
    code: 'PA',
    name: 'Panama',
    slug: 'panama',
  },
  {
    id: 172,
    code: 'PG',
    name: 'Papua New Guinea',
    slug: 'papua-new-guinea',
  },
  {
    id: 173,
    code: 'PY',
    name: 'Paraguay',
    slug: 'paraguay',
  },
  {
    id: 174,
    code: 'PE',
    name: 'Peru',
    slug: 'peru',
  },
  {
    id: 175,
    code: 'PH',
    name: 'Philippines',
    slug: 'philippines',
  },
  {
    id: 176,
    code: 'PN',
    name: 'Pitcairn',
    slug: 'pitcairn',
  },
  {
    id: 177,
    code: 'PL',
    name: 'Poland',
    slug: 'poland',
  },
  {
    id: 178,
    code: 'PT',
    name: 'Portugal',
    slug: 'portugal',
  },
  {
    id: 179,
    code: 'PR',
    name: 'Puerto Rico',
    slug: 'puerto-rico',
  },
  {
    id: 180,
    code: 'QA',
    name: 'Qatar',
    slug: 'qatar',
  },
  {
    id: 181,
    code: 'RE',
    name: 'Réunion',
    slug: 'reunion',
  },
  {
    id: 182,
    code: 'RO',
    name: 'Romania',
    slug: 'romania',
  },
  {
    id: 183,
    code: 'RU',
    name: 'Russian Federation',
    slug: 'russian-federation',
  },
  {
    id: 184,
    code: 'RW',
    name: 'Rwanda',
    slug: 'rwanda',
  },
  {
    id: 185,
    code: 'BL',
    name: 'Saint Barthélemy',
    slug: 'saint-barthelemy',
  },
  {
    id: 186,
    code: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    slug: 'saint-helena-ascension-and-tristan-da-cunha',
  },
  {
    id: 187,
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    slug: 'saint-kitts-and-nevis',
  },
  {
    id: 188,
    code: 'LC',
    name: 'Saint Lucia',
    slug: 'saint-lucia',
  },
  {
    id: 189,
    code: 'MF',
    name: 'Saint Martin (French part)',
    slug: 'saint-martin-french-part',
  },
  {
    id: 190,
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    slug: 'saint-pierre-and-miquelon',
  },
  {
    id: 191,
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    slug: 'saint-vincent-and-the-grenadines',
  },
  {
    id: 192,
    code: 'WS',
    name: 'Samoa',
    slug: 'samoa',
  },
  {
    id: 193,
    code: 'SM',
    name: 'San Marino',
    slug: 'san-marino',
  },
  {
    id: 194,
    code: 'ST',
    name: 'Sao Tome and Principe',
    slug: 'sao-tome-and-principe',
  },
  {
    id: 195,
    code: 'SA',
    name: 'Saudi Arabia',
    slug: 'saudi-arabia',
  },
  {
    id: 196,
    code: 'SN',
    name: 'Senegal',
    slug: 'senegal',
  },
  {
    id: 197,
    code: 'RS',
    name: 'Serbia',
    slug: 'serbia',
  },
  {
    id: 198,
    code: 'SC',
    name: 'Seychelles',
    slug: 'seychelles',
  },
  {
    id: 199,
    code: 'SL',
    name: 'Sierra Leone',
    slug: 'sierra-leone',
  },
  {
    id: 200,
    code: 'SG',
    name: 'Singapore',
    slug: 'singapore',
  },
  {
    id: 201,
    code: 'SX',
    name: 'Sint Maarten (Dutch part)',
    slug: 'sint-maarten-dutch-part',
  },
  {
    id: 202,
    code: 'SK',
    name: 'Slovakia',
    slug: 'slovakia',
  },
  {
    id: 203,
    code: 'SI',
    name: 'Slovenia',
    slug: 'slovenia',
  },
  {
    id: 204,
    code: 'SB',
    name: 'Solomon Islands',
    slug: 'solomon-islands',
  },
  {
    id: 205,
    code: 'SO',
    name: 'Somalia',
    slug: 'somalia',
  },
  {
    id: 206,
    code: 'ZA',
    name: 'South Africa',
    slug: 'south-africa',
  },
  {
    id: 207,
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    slug: 'south-georgia-and-the-south-sandwich-islands',
  },
  {
    id: 208,
    code: 'SS',
    name: 'South Sudan',
    slug: 'south-sudan',
  },
  {
    id: 209,
    code: 'ES',
    name: 'Spain',
    slug: 'spain',
  },
  {
    id: 210,
    code: 'LK',
    name: 'Sri Lanka',
    slug: 'sri-lanka',
  },
  {
    id: 211,
    code: 'SD',
    name: 'Sudan',
    slug: 'sudan',
  },
  {
    id: 212,
    code: 'SR',
    name: 'Suriname',
    slug: 'suriname',
  },
  {
    id: 213,
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    slug: 'svalbard-and-jan-mayen',
  },
  {
    id: 214,
    code: 'SZ',
    name: 'Swaziland',
    slug: 'swaziland',
  },
  {
    id: 215,
    code: 'SE',
    name: 'Sweden',
    slug: 'sweden',
  },
  {
    id: 216,
    code: 'CH',
    name: 'Switzerland',
    slug: 'switzerland',
  },
  {
    id: 217,
    code: 'SY',
    name: 'Syrian Arab Republic',
    slug: 'syrian-arab-republic',
  },
  {
    id: 218,
    code: 'TW',
    name: 'Taiwan, Province of China',
    slug: 'taiwan-province-of-china',
  },
  {
    id: 219,
    code: 'TJ',
    name: 'Tajikistan',
    slug: 'tajikistan',
  },
  {
    id: 220,
    code: 'TZ',
    name: 'Tanzania, United Republic of',
    slug: 'tanzania-united-republic-of',
  },
  {
    id: 221,
    code: 'TH',
    name: 'Thailand',
    slug: 'thailand',
  },
  {
    id: 222,
    code: 'TL',
    name: 'Timor-Leste',
    slug: 'timor-leste',
  },
  {
    id: 223,
    code: 'TG',
    name: 'Togo',
    slug: 'togo',
  },
  {
    id: 224,
    code: 'TK',
    name: 'Tokelau',
    slug: 'tokelau',
  },
  {
    id: 225,
    code: 'TO',
    name: 'Tonga',
    slug: 'tonga',
  },
  {
    id: 226,
    code: 'TT',
    name: 'Trinidad and Tobago',
    slug: 'trinidad-and-tobago',
  },
  {
    id: 227,
    code: 'TN',
    name: 'Tunisia',
    slug: 'tunisia',
  },
  {
    id: 228,
    code: 'TR',
    name: 'Turkey',
    slug: 'turkey',
  },
  {
    id: 229,
    code: 'TM',
    name: 'Turkmenistan',
    slug: 'turkmenistan',
  },
  {
    id: 230,
    code: 'TC',
    name: 'Turks and Caicos Islands',
    slug: 'turks-and-caicos-islands',
  },
  {
    id: 231,
    code: 'TV',
    name: 'Tuvalu',
    slug: 'tuvalu',
  },
  {
    id: 232,
    code: 'UG',
    name: 'Uganda',
    slug: 'uganda',
  },
  {
    id: 233,
    code: 'UA',
    name: 'Ukraine',
    slug: 'ukraine',
  },
  {
    id: 234,
    code: 'AE',
    name: 'United Arab Emirates',
    slug: 'united-arab-emirates',
  },
  {
    id: 235,
    code: 'GB',
    name: 'United Kingdom',
    slug: 'united-kingdom',
  },
  {
    id: 236,
    code: 'US',
    name: 'United States',
    slug: 'united-states',
  },
  {
    id: 237,
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    slug: 'united-states-minor-outlying-islands',
  },
  {
    id: 238,
    code: 'UY',
    name: 'Uruguay',
    slug: 'uruguay',
  },
  {
    id: 239,
    code: 'UZ',
    name: 'Uzbekistan',
    slug: 'uzbekistan',
  },
  {
    id: 240,
    code: 'VU',
    name: 'Vanuatu',
    slug: 'vanuatu',
  },
  {
    id: 241,
    code: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    slug: 'venezuela-bolivarian-republic-of',
  },
  {
    id: 242,
    code: 'VN',
    name: 'Viet Nam',
    slug: 'viet-nam',
  },
  {
    id: 243,
    code: 'VG',
    name: 'Virgin Islands, British',
    slug: 'virgin-islands-british',
  },
  {
    id: 244,
    code: 'VI',
    name: 'Virgin Islands, U.S.',
    slug: 'virgin-islands-us',
  },
  {
    id: 245,
    code: 'WF',
    name: 'Wallis and Futuna',
    slug: 'wallis-and-futuna',
  },
  {
    id: 246,
    code: 'EH',
    name: 'Western Sahara',
    slug: 'western-sahara',
  },
  {
    id: 247,
    code: 'YE',
    name: 'Yemen',
    slug: 'yemen',
  },
  {
    id: 248,
    code: 'ZM',
    name: 'Zambia',
    slug: 'zambia',
  },
  {
    id: 249,
    code: 'ZW',
    name: 'Zimbabwe',
    slug: 'zimbabwe',
  },
];

export const COUNTRY_OPTIONS_ISO = Countries.map((country) => ({
  value: country.code,
  label: country.name,
}));
