/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Origin Energy API
 * Swagger documentation for the Origin Energy API for reading and storing metered data
 * OpenAPI spec version: 0.1
 */
export interface ReadDTO {
  timestamp: string;
  value: number;
}

export type Aggregate = 'sum' | 'mean';

export const Aggregate = {
  sum: 'sum' as Aggregate,
  mean: 'mean' as Aggregate,
};

export interface AggregatedReadDTO {
  start: string;
  stop: string;
  value: number;
}

export type Unit = 'Wh' | 'kWh' | 'MWh' | 'GWh';

export const Unit = {
  Wh: 'Wh' as Unit,
  kWh: 'kWh' as Unit,
  MWh: 'MWh' as Unit,
  GWh: 'GWh' as Unit,
};

export interface MeasurementDTO {
  reads: ReadDTO[];
  unit: Unit;
}

export type ReadsControllerGetReadsParams = {
  start: string;
  end: string;
  limit?: number;
  offset?: number;
};

export type ReadsControllerGetReadsDifferenceParams = {
  start: string;
  end: string;
  limit?: number;
  offset?: number;
};

export type ReadsControllerGetReadsAggregatesParams = {
  start: string;
  end: string;
  window: string;
  aggregate: Aggregate;
  difference: boolean;
};
