CREATE TABLE public.configuration (
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    id integer DEFAULT 1 NOT NULL,
    "countryName" character varying,
    currencies text,
    regions text,
    "externalDeviceIdTypes" text,
    "contractsLookup" text,
    "complianceStandard" character varying,
    "deviceTypes" text,
    CONSTRAINT "CHK_3c3716a6563ee58bdf448a8c4e" CHECK ((id = 1))
);

CREATE TABLE public."user" (
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    id integer NOT NULL,
    title character varying NOT NULL,
    "firstName" character varying NOT NULL,
    "lastName" character varying NOT NULL,
    email character varying NOT NULL,
    telephone character varying NOT NULL,
    password character varying NOT NULL,
    "blockchainAccountAddress" character varying,
    "blockchainAccountSignedMessage" character varying,
    notifications boolean,
    "autoPublish" text,
    rights integer DEFAULT 0 NOT NULL,
    "organizationId" integer
);

CREATE TABLE public.organization (
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    id integer NOT NULL,
    "activeCountries" character varying NOT NULL,
    code character varying NOT NULL,
    name character varying NOT NULL,
    contact character varying NOT NULL,
    telephone character varying NOT NULL,
    email character varying NOT NULL,
    address character varying NOT NULL,
    shareholders character varying NOT NULL,
    "ceoPassportNumber" character varying,
    "ceoName" character varying NOT NULL,
    "companyNumber" character varying,
    "vatNumber" character varying NOT NULL,
    postcode character varying NOT NULL,
    "headquartersCountry" integer NOT NULL,
    country integer NOT NULL,
    "businessTypeSelect" character varying NOT NULL,
    "businessTypeInput" character varying,
    "yearOfRegistration" integer NOT NULL,
    "numberOfEmployees" integer NOT NULL,
    website character varying NOT NULL,
    status integer NOT NULL,
    "leadUserId" integer
);

CREATE TABLE public.device (
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    id integer NOT NULL,
    status integer NOT NULL,
    "facilityName" character varying NOT NULL,
    description character varying NOT NULL,
    images character varying NOT NULL,
    address character varying NOT NULL,
    region character varying NOT NULL,
    province character varying NOT NULL,
    country character varying NOT NULL,
    "operationalSince" integer NOT NULL,
    "capacityInW" integer NOT NULL,
    "gpsLatitude" character varying NOT NULL,
    "gpsLongitude" character varying NOT NULL,
    timezone character varying NOT NULL,
    "deviceType" character varying NOT NULL,
    "complianceRegistry" character varying NOT NULL,
    "otherGreenAttributes" character varying NOT NULL,
    "typeOfPublicSupport" character varying NOT NULL,
    "lastSmartMeterReading" text,
    "deviceGroup" character varying NOT NULL,
    "smartMeterReads" text NOT NULL,
    "externalDeviceIds" text,
    "organizationId" integer NOT NULL
);