export const ORIGIN_ENVIRONMENT = 'ORIGIN_ENVIRONMENT';
export const ORIGIN_CONFIGURATION = 'ORIGIN_CONFIGURATION';
export const ORIGIN_USER = 'ORIGIN_USER';
export const AUTHENTICATION_TOKEN = 'AUTHENTICATION_TOKEN';
export const ORIGIN_LANGUAGE = 'ORIGIN_LANGUAGE';
