/*
 * Generated by orval v5.0.0-alpha.9 🍺
 * Do not edit manually.
 * Exchange API
 * Swagger documentation for the Exchange API
 * OpenAPI spec version: 0.1
 */
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
} from 'react-query';
import type { AccountDTO } from './exchangeAPI.schemas';
import { customMutator } from '../mutator/custom-mutator';

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const accountControllerGetAccount = <Data = unknown>() => {
  return customMutator<Data extends unknown ? AccountDTO : Data>({
    url: `/api/account`,
    method: 'get',
  });
};

export const getAccountControllerGetAccountQueryKey = () => [`/api/account`];

export const useAccountControllerGetAccount = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  queryConfig?: UseQueryOptions<
    AsyncReturnType<typeof accountControllerGetAccount>,
    Error
  >
) => {
  const queryKey = getAccountControllerGetAccountQueryKey();

  const query = useQuery<
    AsyncReturnType<typeof accountControllerGetAccount>,
    Error
  >(queryKey, () => accountControllerGetAccount<Data>(), queryConfig);

  return {
    queryKey,
    ...query,
  };
};

export const accountControllerCreate = <Data = unknown>() => {
  return customMutator<Data extends unknown ? unknown : Data>({
    url: `/api/account`,
    method: 'post',
    data: undefined,
  });
};

export const useAccountControllerCreate = <
  Data extends unknown = unknown,
  Error extends unknown = unknown
>(
  mutationConfig?: UseMutationOptions<
    AsyncReturnType<typeof accountControllerCreate>,
    Error
  >
) => {
  return useMutation<AsyncReturnType<typeof accountControllerCreate>, Error>(
    () => {
      return accountControllerCreate<Data>();
    },
    mutationConfig
  );
};
