sudo: required
dist: trusty
language: node_js
node_js:
  - '10.0.0'

install:
  - travis_wait npm install

before_script:
  - npm run start-ganache > /dev/null &
  - sleep 1
  - npm run start-test-backend > /dev/null &
  - sleep 1
 
script:
  - npm test